"""add_user_fields_schedule_culto_fk

Revision ID: cccd1f3cbdb5
Revises: fc0cd0a8df31
Create Date: 2026-05-13 15:36:38.726275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cccd1f3cbdb5'
down_revision: Union[str, Sequence[str], None] = 'fc0cd0a8df31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escalas', sa.Column('culto_id', sa.Integer(), nullable=True))
    op.add_column('escalas', sa.Column('observacoes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'escalas', 'cultos', ['culto_id'], ['id'])
    op.add_column('usuarios', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('cargo', sa.String(length=20), server_default='Voluntário', nullable=False))
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('usuarios', sa.Column('data_entrada', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'data_entrada')
    op.drop_column('usuarios', 'ativo')
    op.drop_column('usuarios', 'cargo')
    op.drop_column('usuarios', 'email')
    op.drop_constraint(None, 'escalas', type_='foreignkey')
    op.drop_column('escalas', 'observacoes')
    op.drop_column('escalas', 'culto_id')
    # ### end Alembic commands ###
