"""Adicionando tabelas e relacionamentos

Revision ID: ce9c489b9dc5
Revises: cccd1f3cbdb5
Create Date: 2026-05-13 15:48:32.654894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9c489b9dc5'
down_revision: Union[str, Sequence[str], None] = 'cccd1f3cbdb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
